version: 9.0.0-alpha{build}
branches:
  only:
  - master
skip_tags: true
max_jobs: 1
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
install:
- git submodule update --init --recursive
build_script:
- cmd: dotnet build -c Release
test_script:
- cmd: dotnet test -c Release
artifacts:
- path: '**/Release/*.nupkg'
